services:
  nestexample:
      image: nestexample
      build:
        context: .
        dockerfile: ./Dockerfile
      environment:
        NODE_ENV: production
        JWT_SECRET: "JWT_SECRET"
        DATABASE_URL: mysql://prisma:prisma@mysql:3306/users
      depends_on:
        mysql:
          condition: service_healthy
      restart: "on-failure"

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - nestexample
    ports:
      - 3000:3000

  mysql:
    image: mysql:8.0
    command: --lower_case_table_names=1
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users
      - MYSQL_USER=prisma 
      - MYSQL_PASSWORD=prisma
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h127.0.0.1', '-P3306']
      interval: 5s
      timeout: 2s
      retries: 20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: prisma
      PMA_PASSWORD: prisma

volumes:
  db_data:
